# Generated by Django 6.0.6 on 2026-08-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobview",
            name="job",
        ),
        migrations.RemoveField(
            model_name="jobview",
            name="user",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="user",
        ),
        migrations.DeleteModel(
            name="JobClick",
        ),
        migrations.DeleteModel(
            name="JobView",
        ),
        migrations.DeleteModel(
            name="SearchLog",
        ),
    ]
