# Generated by Django 6.0.6 on 2026-06-28 21:40

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0002_company_careers_page_url_company_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RashidConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_provider",
                    models.CharField(
                        choices=[
                            ("bedrock", "Amazon Bedrock"),
                            ("anthropic", "Anthropic API"),
                        ],
                        default="bedrock",
                        max_length=20,
                    ),
                ),
                (
                    "bedrock_region",
                    models.CharField(default="us-east-1", max_length=30),
                ),
                (
                    "bedrock_model_id",
                    models.CharField(
                        default="anthropic.claude-sonnet-4-20250514-v1:0",
                        max_length=100,
                    ),
                ),
                (
                    "anthropic_model",
                    models.CharField(default="claude-sonnet-4", max_length=50),
                ),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=2000)),
                (
                    "system_prompt",
                    models.TextField(
                        default='اسمي راشد. أنا مرشد مهني شخصي ومتخصص.\nبتكلم بالعربية العامية المصرية بشكل طبيعي ومريح.\n\nأسلوبي صريح ومحترم وعملي. مش بدّوش معلومات وبدي للموضوع.\nكل شخص عندي حالة مستقلة ليها ظروفها ومهاراتها وأهدافها.\n\nبسأل سؤال واحد في كل مرة وبستنى الإجابة قبل ما أكمل.\nمش بوعد بوعود مستحيلة ومش بقول "اتعلم Python في 7 أيام".\n\nبساعدك توصل لهدفك الحقيقي بخطة واقعية تناسب وقتك وظروفك.'
                    ),
                ),
                (
                    "dialect_config",
                    models.TextField(
                        default="Egyptian Colloquial Arabic Guidelines:\n- Use إيه instead of ما\n- Use عايز/عاوز instead of أريد  \n- Use ازاي instead of كيف\n- Use ليه instead of لماذا\n- Use ممكن instead of يمكن\n- Use علشان instead of لأن\nNatural conversational tone, not formal Arabic."
                    ),
                ),
                (
                    "onboarding_questions",
                    models.JSONField(
                        default=list, help_text="List of questions for first-time users"
                    ),
                ),
                (
                    "daily_token_limit",
                    models.IntegerField(
                        default=100000, help_text="Maximum tokens per user per day"
                    ),
                ),
                (
                    "max_conversation_len",
                    models.IntegerField(
                        default=50, help_text="Maximum messages per conversation"
                    ),
                ),
                (
                    "auto_delete_after_days",
                    models.IntegerField(
                        default=90, help_text="Delete conversations older than this"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rashid Configuration",
                "verbose_name_plural": "Rashid Configuration",
            },
        ),
        migrations.CreateModel(
            name="RashidConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("general", "General Chat"),
                            ("career_path", "Career Path Planning"),
                            ("cv_review", "CV Review"),
                            ("linkedin", "LinkedIn Optimizer"),
                            ("cover_letter", "Cover Letter Generator"),
                            ("interview_prep", "Interview Preparation"),
                            ("course_advisor", "Course Advisor"),
                            ("salary_negotiation", "Salary Negotiation"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Job being discussed (for 'Ask Rashid about this job')",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rashid_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rashid Conversation",
                "verbose_name_plural": "Rashid Conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RashidMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", encrypted_model_fields.fields.EncryptedTextField()),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="rashid.rashidconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rashid Message",
                "verbose_name_plural": "Rashid Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RashidProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience_level", models.CharField(blank=True, max_length=20)),
                ("current_role", models.CharField(blank=True, max_length=100)),
                ("current_situation", models.TextField(blank=True)),
                ("target_role", models.CharField(blank=True, max_length=100)),
                ("skills", models.JSONField(default=list)),
                ("skill_gaps", models.JSONField(default=list)),
                (
                    "constraints",
                    models.JSONField(
                        default=dict, help_text="Time, location, financial constraints"
                    ),
                ),
                ("career_path", models.JSONField(blank=True, null=True)),
                ("action_plan", models.JSONField(blank=True, null=True)),
                ("onboarding_complete", models.BooleanField(default=False)),
                ("onboarding_step", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rashid_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rashid User Profile",
                "verbose_name_plural": "Rashid User Profiles",
            },
        ),
        migrations.CreateModel(
            name="RashidStoryBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("situation", models.TextField()),
                ("task", models.TextField()),
                ("action", models.TextField()),
                ("result", models.TextField()),
                ("reflection", models.TextField(blank=True)),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Skills/competencies demonstrated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="star_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "STAR Story",
                "verbose_name_plural": "STAR Stories",
            },
        ),
        migrations.CreateModel(
            name="RashidUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rashid_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rashid Usage",
                "verbose_name_plural": "Rashid Usage",
                "unique_together": {("user", "date")},
            },
        ),
    ]
