# Generated by Django 6.0.6 on 2026-08-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rashid", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rashidconfig",
            name="bedrock_model_id",
            field=models.CharField(
                default="us.anthropic.claude-sonnet-4-20250514-v1:0", max_length=100
            ),
        ),
    ]
