# Generated by Django 6.0.6 on 2026-08-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rashid", "0002_fix_bedrock_model_id_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rashidconfig",
            name="anthropic_model",
            field=models.CharField(default="claude-sonnet-4-5", max_length=50),
        ),
        migrations.AlterField(
            model_name="rashidconfig",
            name="bedrock_model_id",
            field=models.CharField(
                default="us.anthropic.claude-sonnet-4-5-20250929-v1:0", max_length=100
            ),
        ),
    ]
