# Generated by Django 6.0.6 on 2026-10-02 23:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0012_source_adaptive_allowed_source_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScraperRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=30)),
                (
                    "strategy_tier",
                    models.CharField(
                        blank=True,
                        help_text="Which StrategyRouter tier handled this run (STRUCTURED/HTTP/BROWSER/ADAPTIVE/AI/AGENTIC)",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("fetched", models.IntegerField(default=0)),
                ("normalized", models.IntegerField(default=0)),
                ("created", models.IntegerField(default=0)),
                ("updated", models.IntegerField(default=0)),
                ("duplicates", models.IntegerField(default=0)),
                ("verified", models.IntegerField(default=0)),
                ("errors", models.IntegerField(default=0)),
                ("publishable", models.IntegerField(default=0)),
                ("indexed", models.IntegerField(default=0)),
                (
                    "direct_apply_candidates",
                    models.IntegerField(
                        default=0,
                        help_text="Jobs that had a non-empty apply URL to evaluate",
                    ),
                ),
                (
                    "direct_apply_verified",
                    models.IntegerField(
                        default=0,
                        help_text="Jobs whose apply URL passed the direct/moat gate",
                    ),
                ),
                ("rejected_total", models.IntegerField(default=0)),
                ("rejected_breakdown", models.JSONField(blank=True, default=dict)),
                ("degraded", models.BooleanField(db_index=True, default=False)),
                (
                    "zero_yield_anomaly",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraper_runs",
                        to="jobs.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scraper Run",
                "verbose_name_plural": "Scraper Runs",
                "db_table": "scraper_run",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "-started_at"],
                        name="scraper_run_source_time_idx",
                    )
                ],
            },
        ),
    ]
