# Generated by Django 4.2.16 on 2026-08-06 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_remove_job_remote_type_job_work_arrangement_and_more'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('search', 'Search Results'), ('recommendation', 'AI Recommendation'), ('profile_view', 'Profile View'), ('skill_match', 'Skill Match Alert')], max_length=50)),
                ('search_query', models.TextField(blank=True)),
                ('matched_skills', models.JSONField(default=list, help_text='Skills that triggered this discovery')),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('saved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_discoveries', to='employers.employerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_discoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talent Discovery',
                'verbose_name_plural': 'Talent Discoveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnockoutQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Answer'), ('yes_no', 'Yes/No'), ('select', 'Multiple Choice')], max_length=20)),
                ('required_answer', models.JSONField(default=dict, help_text='Expected answer(s) for passing')),
                ('pass_if_matches', models.BooleanField(default=True, help_text="Pass if answer matches (True) or doesn't match (False)")),
                ('weight', models.FloatField(default=1.0, help_text='Weight of this question in overall score')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_questions', to='employers.employerprofile')),
            ],
            options={
                'verbose_name': 'Knockout Question',
                'verbose_name_plural': 'Knockout Questions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(help_text='AI-computed match score (0-1)')),
                ('skill_match_score', models.FloatField(help_text='Skills match score (0-1)')),
                ('experience_score', models.FloatField(help_text='Experience match score (0-1)')),
                ('education_score', models.FloatField(help_text='Education match score (0-1)')),
                ('salary_expectation_score', models.FloatField(help_text='Salary expectation alignment (0-1)')),
                ('knockout_passed', models.BooleanField(default=True)),
                ('knockout_failures', models.JSONField(default=list, help_text='List of failed knockout questions')),
                ('explanations', models.JSONField(default=dict, help_text='AI-generated explanations for ranking')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ranked', 'Ranked'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ranked_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_rankings', to='employers.employerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_rankings', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Ranking',
                'verbose_name_plural': 'Candidate Rankings',
                'ordering': ['-overall_score', 'ranked_at'],
                'unique_together': {('job', 'user')},
            },
        ),
    ]
