# Generated by Django 6.0.6 on 2026-08-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0005_employerteammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentdiscovery",
            name="was_discoverable_at_creation",
            field=models.BooleanField(
                default=False,
                help_text="Snapshot of user's is_discoverable consent at time of discovery",
            ),
        ),
        migrations.AddField(
            model_name="talentpoolcandidate",
            name="was_discoverable_at_creation",
            field=models.BooleanField(
                default=False,
                help_text="Snapshot of user's is_discoverable consent at time of addition",
            ),
        ),
    ]
