# Generated by Django 6.0.6 on 2026-10-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0006_add_was_discoverable_at_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="verification_note",
            field=models.TextField(
                blank=True,
                help_text="Optional context the employer provides when requesting verification",
            ),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="verification_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
