# Generated by Django 4.2.16 on 2026-08-07 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('batch_type', models.CharField(choices=[('digest', 'Digest'), ('alert', 'Alert'), ('campaign', 'Campaign'), ('system', 'System')], db_index=True, max_length=20)),
                ('total_notifications', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Notification Batch',
                'verbose_name_plural': 'Notification Batches',
                'db_table': 'notification_batch',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('job_match', 'Job Match'), ('new_job', 'New Job'), ('interview_invite', 'Interview Invite'), ('interview_reminder', 'Interview Reminder'), ('profile_view', 'Profile View'), ('message_response', 'Message Response'), ('application_update', 'Application Update'), ('skill_badge', 'Skill Badge'), ('score_improvement', 'Score Improvement'), ('weekly_digest', 'Weekly Digest'), ('system', 'System'), ('promotional', 'Promotional')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_id', models.CharField(blank=True, help_text='ID of related object (job, interview, etc.)', max_length=100)),
                ('related_type', models.CharField(blank=True, help_text='Type of related object', max_length=50)),
                ('related_url', models.URLField(blank=True, help_text='URL to related content')),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], db_index=True, default='unread', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification expires', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'db_table': 'user_notification',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('alert_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='instant', help_text='How often to send notifications', max_length=20)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_digest_enabled', models.BooleanField(default=True)),
                ('email_digest_time', models.TimeField(blank=True, help_text='Time to send daily/weekly digests', null=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('notify_job_matches', models.BooleanField(default=True)),
                ('notify_new_jobs', models.BooleanField(default=True)),
                ('notify_interview_invites', models.BooleanField(default=True)),
                ('notify_interview_reminders', models.BooleanField(default=True)),
                ('notify_profile_views', models.BooleanField(default=True)),
                ('notify_message_responses', models.BooleanField(default=True)),
                ('notify_application_updates', models.BooleanField(default=True)),
                ('notify_skill_badges', models.BooleanField(default=True)),
                ('notify_score_improvements', models.BooleanField(default=True)),
                ('notify_weekly_digest', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time for quiet hours (24-hour format)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time for quiet hours (24-hour format)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preference',
            },
        ),
    ]
