# Generated by Django 6.0.6 on 2026-10-06 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0015_businesscontact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachSuppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unsubscribe", "Unsubscribed"),
                            ("bounce", "Hard Bounce"),
                            ("manual", "Manual Suppression"),
                        ],
                        max_length=15,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Outreach Suppression",
                "verbose_name_plural": "Outreach Suppressions",
                "db_table": "outreach_suppression",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutreachTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("subject", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(
                        help_text="Supports {{company_name}} and {{contact_role}} only"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Outreach Template",
                "verbose_name_plural": "Outreach Templates",
                "db_table": "outreach_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OutreachCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("dry_run", "Dry Run"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "rate_limit_per_day",
                    models.IntegerField(
                        default=50,
                        help_text="Max messages this campaign may LOG (dry-run) per day - a real-world sending courtesy limit, enforced even in dry-run mode so campaign behavior is representative of what a real send would respect.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outreach_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="outreach.outreachtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outreach Campaign",
                "verbose_name_plural": "Outreach Campaigns",
                "db_table": "outreach_campaign",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutreachMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dry_run_logged", "Dry Run Logged"),
                            ("suppressed", "Suppressed"),
                            ("rate_limited", "Rate Limited"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("suppression_reason", models.CharField(blank=True, max_length=200)),
                ("rendered_subject", models.CharField(blank=True, max_length=200)),
                ("rendered_body", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="outreach.outreachcampaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_messages",
                        to="jobs.businesscontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outreach Message",
                "verbose_name_plural": "Outreach Messages",
                "db_table": "outreach_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutreachResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("reply", "Reply"),
                            ("bounce", "Bounce"),
                            ("unsubscribe", "Unsubscribe"),
                        ],
                        max_length=15,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="outreach.outreachmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outreach Response",
                "verbose_name_plural": "Outreach Responses",
                "db_table": "outreach_response",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="outreachmessage",
            index=models.Index(
                fields=["campaign", "status"], name="outreach_msg_camp_status_idx"
            ),
        ),
    ]
