# Generated by Django 4.2.16 on 2026-08-06 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UptimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded')], help_text='The service status', max_length=20)),
                ('downtime_minutes', models.FloatField(blank=True, help_text='Downtime duration in minutes if down', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if down', null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the uptime record was created')),
            ],
            options={
                'verbose_name': 'Uptime Record',
                'verbose_name_plural': 'Uptime Records',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['status', 'recorded_at'], name='monitoring__status_01a623_idx'), models.Index(fields=['-recorded_at'], name='monitoring__recorde_b45732_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('cpu_percent', 'CPU Usage (%)'), ('memory_percent', 'Memory Usage (%)'), ('disk_percent', 'Disk Usage (%)'), ('request_count', 'Request Count'), ('error_count', 'Error Count'), ('response_time_avg', 'Average Response Time (ms)'), ('response_time_p95', '95th Percentile Response Time (ms)'), ('response_time_p99', '99th Percentile Response Time (ms)'), ('active_users', 'Active Users'), ('jobs_scraped', 'Jobs Scraped'), ('api_calls', 'API Calls')], help_text='The type of metric', max_length=50)),
                ('value', models.FloatField(help_text='The metric value')),
                ('tags', models.JSONField(blank=True, help_text="Additional tags for filtering (e.g., {'endpoint': '/api/v1/jobs'})", null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the metric was recorded')),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_type', 'recorded_at'], name='monitoring__metric__5a4291_idx'), models.Index(fields=['recorded_at'], name='monitoring__recorde_a5b928_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('database', 'Database'), ('redis', 'Redis'), ('qdrant', 'Qdrant'), ('celery', 'Celery'), ('sentry', 'Sentry'), ('api', 'API')], help_text='The system component being checked', max_length=50)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], help_text='The health status', max_length=20)),
                ('response_time_ms', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if unhealthy', null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the health check was performed')),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Checks',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['component', 'status'], name='monitoring__compone_112b41_idx'), models.Index(fields=['-checked_at'], name='monitoring__checked_55eb44_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], help_text='The log level', max_length=20)),
                ('message', models.TextField(help_text='The error message')),
                ('traceback', models.TextField(blank=True, help_text='Full traceback if available', null=True)),
                ('extra_data', models.JSONField(blank=True, help_text='Additional data (user_id, request_id, etc.)', null=True)),
                ('sentry_id', models.CharField(blank=True, help_text='Sentry event ID if sent', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the error was logged')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='monitoring__level_00ac11_idx'), models.Index(fields=['created_at'], name='monitoring__created_49ec08_idx')],
            },
        ),
    ]
