# Generated by Django 6.0.6 on 2026-08-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcheck",
            name="component",
            field=models.CharField(
                choices=[
                    ("database", "Database"),
                    ("redis", "Redis"),
                    ("celery", "Celery"),
                    ("sentry", "Sentry"),
                    ("api", "API"),
                ],
                help_text="The system component being checked",
                max_length=50,
            ),
        ),
    ]
