# Generated by Django 6.0.6 on 2026-06-28 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_company_careers_page_url_company_description_and_more"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv_file",
                    models.FileField(blank=True, null=True, upload_to="cvs/%Y/%m/"),
                ),
                ("cv_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("cv_parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cv_parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("portfolio_url", models.URLField(blank=True)),
                ("skills", models.JSONField(default=list)),
                ("experience_years", models.IntegerField(default=0)),
                ("education", models.JSONField(default=list)),
                ("languages", models.JSONField(default=list)),
                ("certifications", models.JSONField(default=list)),
                ("current_role", models.CharField(blank=True, max_length=100)),
                ("desired_roles", models.JSONField(default=list)),
                ("desired_locations", models.JSONField(default=list)),
                ("preferred_type", models.CharField(blank=True, max_length=20)),
                ("open_to_remote", models.BooleanField(default=True)),
                ("min_salary", models.IntegerField(blank=True, null=True)),
                ("salary_currency", models.CharField(default="EGP", max_length=3)),
                ("email_alerts", models.BooleanField(default=True)),
                (
                    "alert_frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="instant",
                        max_length=10,
                    ),
                ),
                (
                    "min_match_score",
                    models.IntegerField(
                        default=70,
                        help_text="Only alert for jobs scoring above this threshold",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="JobMatchScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(help_text="0-100 score")),
                (
                    "breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Breakdown by dimension: {title:85, skills:72, ...}",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_matches",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Match Score",
                "verbose_name_plural": "Job Match Scores",
                "indexes": [
                    models.Index(
                        fields=["user", "-score"], name="users_jobma_user_id_00d386_idx"
                    )
                ],
                "unique_together": {("user", "job")},
            },
        ),
    ]
