# Generated by Django 6.0.6 on 2026-09-29 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_job_field_provenance"),
        ("users", "0004_convert_min_match_score_to_float"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[
                            ("impression", "Impression"),
                            ("view", "View"),
                            ("save", "Save"),
                            ("apply", "Apply"),
                            ("dismiss", "Dismiss"),
                            ("not_interested", "Not Interested"),
                            ("interview", "Interview"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedback",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation Feedback",
                "verbose_name_plural": "Recommendation Feedback",
                "db_table": "users_recommendation_feedback",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "signal"], name="users_recom_user_id_d5e464_idx"
                    ),
                    models.Index(
                        fields=["job", "signal"], name="users_recom_job_id_d85557_idx"
                    ),
                ],
                "unique_together": {("user", "job", "signal")},
            },
        ),
    ]
