# Generated by Django 6.0.6 on 2026-06-28 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=100, unique=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("never", "Never Run"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                (
                    "last_duration",
                    models.FloatField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("run_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pipeline Health",
                "verbose_name_plural": "Pipeline Health",
                "ordering": ["task_name"],
            },
        ),
        migrations.CreateModel(
            name="ProxyPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=200)),
                ("port", models.IntegerField()),
                ("username", models.CharField(blank=True, max_length=100)),
                ("password", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("fail_count", models.IntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Proxy",
                "verbose_name_plural": "Proxy Pool",
            },
        ),
        migrations.AlterField(
            model_name="media",
            name="size",
            field=models.PositiveIntegerField(help_text="File size in bytes"),
        ),
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scrape_interval_hours",
                    models.IntegerField(
                        default=6, help_text="How often to run full scrape"
                    ),
                ),
                (
                    "url_verify_interval_h",
                    models.IntegerField(
                        default=24, help_text="How often to verify apply URLs"
                    ),
                ),
                (
                    "legitimacy_threshold",
                    models.FloatField(
                        default=0.6, help_text="Minimum legitimacy score (0.0-1.0)"
                    ),
                ),
                (
                    "max_job_age_days",
                    models.IntegerField(
                        default=90, help_text="Auto-expire jobs older than this"
                    ),
                ),
                (
                    "min_match_score_alert",
                    models.IntegerField(
                        default=70, help_text="Minimum score to trigger job alert"
                    ),
                ),
                (
                    "max_alerts_per_day",
                    models.IntegerField(
                        default=5, help_text="Maximum job alerts per user per day"
                    ),
                ),
                (
                    "match_weights",
                    models.JSONField(
                        default=dict, help_text="Scoring weights by dimension"
                    ),
                ),
                (
                    "email_rotation_mode",
                    models.CharField(
                        choices=[
                            ("round_robin", "Round Robin"),
                            ("least_used", "Least Used"),
                            ("priority", "Priority Order"),
                        ],
                        default="round_robin",
                        max_length=20,
                    ),
                ),
                (
                    "digest_weekday",
                    models.IntegerField(default=1, help_text="1=Monday, 7=Sunday"),
                ),
                (
                    "digest_hour",
                    models.IntegerField(
                        default=9, help_text="Hour to send digest (0-23)"
                    ),
                ),
                (
                    "re_engagement_days",
                    models.IntegerField(
                        default=7,
                        help_text="Send re-engagement email after X days inactive",
                    ),
                ),
                (
                    "require_admin_job_review",
                    models.BooleanField(
                        default=False,
                        help_text="Require admin approval for employer-posted jobs",
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Configuration",
                "verbose_name_plural": "Platform Configuration",
            },
        ),
    ]
