# Generated by Django 4.2.16 on 2026-08-06 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_pipelinehealth_proxypool_alter_media_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('job', 'Job Quality'), ('user', 'User Profile'), ('career', 'Career Progression'), ('notification', 'Notifications'), ('employer', 'Employer Actions'), ('celebration', 'Milestones')], db_index=True, max_length=30)),
                ('conditions', models.JSONField(default=dict, help_text="Condition tree: {operator: 'ALL'|'ANY'|'NOT', conditions: [...], field, operator, value}")),
                ('action_type', models.CharField(choices=[('recommend', 'Recommend'), ('alert', 'Alert'), ('flag', 'Flag'), ('remind', 'Remind'), ('celebrate', 'Celebrate'), ('recommend_employer', 'Recommend to Employer'), ('request_cv_update', 'Request CV Update')], db_index=True, max_length=30)),
                ('action_params', models.JSONField(default=dict, help_text='Action-specific parameters')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'db_table': 'core_rule',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='featureflag',
            name='category',
            field=models.CharField(blank=True, help_text='Feature category for grouping', max_length=50),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='employer_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='enabled_for_users',
            field=models.JSONField(default=list, help_text='List of user IDs who have this feature enabled'),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='enabled_percentage',
            field=models.IntegerField(default=0, help_text='Percentage of users to enable this feature for (0-100)'),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='regions',
            field=models.JSONField(default=list, help_text='List of regions where this feature is enabled'),
        ),
        migrations.CreateModel(
            name='PortfolioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('url', models.URLField()),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('technologies', models.JSONField(default=list, help_text='List of technologies detected')),
                ('projects', models.JSONField(default=list, help_text='List of projects with details')),
                ('quality_score', models.FloatField(blank=True, help_text='AI-calculated quality score (0-1)', null=True)),
                ('completeness_score', models.FloatField(blank=True, help_text='How complete the portfolio is (0-1)', null=True)),
                ('tech_stack', models.JSONField(default=dict, help_text='Detailed tech stack breakdown')),
                ('project_count', models.IntegerField(default=0)),
                ('star_count', models.IntegerField(default=0)),
                ('contribution_count', models.IntegerField(default=0)),
                ('observations', models.JSONField(default=dict, help_text='AI-generated observations about the portfolio')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Analysis',
                'verbose_name_plural': 'Portfolio Analyses',
                'db_table': 'core_portfolio_analysis',
            },
        ),
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('github_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('profile_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Connection',
                'verbose_name_plural': 'GitHub Connections',
                'db_table': 'core_github_connection',
            },
        ),
    ]
