# Generated by Django 6.0.6 on 2026-08-30 19:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rule_featureflag_category_featureflag_employer_only_and_more"),
        ("jobs", "0006_add_github_org_to_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "feature_flags",
                    models.JSONField(
                        default=list,
                        help_text="List of FeatureFlag keys this plan unlocks",
                    ),
                ),
                (
                    "job_posting_limit",
                    models.IntegerField(
                        default=5, help_text="Max active job postings. 0 = unlimited."
                    ),
                ),
                (
                    "candidate_search_limit",
                    models.IntegerField(
                        default=50,
                        help_text="Max candidate discoveries per month. 0 = unlimited.",
                    ),
                ),
                (
                    "ai_features_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether AI-powered features (ranking, matching) are available",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "core_subscription_plan",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="jobs.company",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="core.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "core_company_subscription",
                "ordering": ["-started_at"],
            },
        ),
    ]
