# Generated by Django 6.0.6 on 2026-10-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="seat_limit",
            field=models.IntegerField(
                default=0,
                help_text="Max active team seats for a company on this plan. 0 = unlimited.",
            ),
        ),
    ]
