# Generated by Django 6.0.6 on 2026-06-28 21:40

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "smtp_host",
                    models.CharField(default="smtp.gmail.com", max_length=100),
                ),
                ("smtp_port", models.IntegerField(default=587)),
                ("username_enc", encrypted_model_fields.fields.EncryptedCharField()),
                ("password_enc", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "daily_limit",
                    models.IntegerField(
                        default=500, help_text="Maximum emails per day"
                    ),
                ),
                ("today_sent", models.IntegerField(default=0)),
                ("last_reset", models.DateField(auto_now_add=True)),
                (
                    "rotation_order",
                    models.IntegerField(
                        default=0, help_text="Order in rotation queue (0 = first)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("total_sent", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("tracking_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Email Account",
                "verbose_name_plural": "Email Accounts",
                "ordering": ["rotation_order"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Email"),
                            ("job_alert", "Job Alert"),
                            ("weekly_digest", "Weekly Digest"),
                            ("employer_application", "Employer: New Application"),
                            ("employer_url_dead", "Employer: Dead Apply URL"),
                            ("re_engagement", "Re-engagement Email"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Supports {{variables}}", max_length=200
                    ),
                ),
                ("html_body", models.TextField()),
                (
                    "text_body",
                    models.TextField(blank=True, help_text="Plain text fallback"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("total_sent", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("opened", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked", models.BooleanField(default=False)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("tracking_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("failed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to="emails.emailaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="emails.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
