# Generated by Django 6.0.6 on 2026-08-31 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this prompt (e.g., 'cover_letter_generation')",
                        max_length=100,
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("cover_letter", "Cover Letter Generation"),
                            ("cv_tailor", "CV Tailoring"),
                            ("match_explanation", "Job Match Explanation"),
                            ("interview_questions", "Interview Question Generation"),
                            ("interview_evaluation", "Interview Answer Evaluation"),
                            ("skill_extraction", "Skill Extraction from Jobs"),
                            ("rashid_career_advice", "Rashid Career Advice"),
                            ("rashid_interview_prep", "Rashid Interview Prep"),
                            ("weekly_digest_tip", "Weekly Digest Career Tip"),
                        ],
                        db_index=True,
                        help_text="Which feature uses this prompt",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version number (increments on each edit)"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The actual prompt text. Use {variable} for template variables."
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, help_text="Optional system prompt (Claude-specific)"
                    ),
                ),
                (
                    "model_target",
                    models.CharField(
                        choices=[
                            ("haiku", "Claude 3.5 Haiku"),
                            ("sonnet", "Claude 3.5 Sonnet"),
                            ("opus", "Claude Opus"),
                        ],
                        default="haiku",
                        help_text="Which AI model this prompt is optimized for",
                        max_length=20,
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=1000, help_text="Maximum tokens for completion"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Sampling temperature (0.0 = deterministic, 1.0 = creative)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only one version per name can be active",
                    ),
                ),
                (
                    "is_test",
                    models.BooleanField(
                        default=False, help_text="Mark as test version for A/B testing"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Change notes, why this version was created",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_prompt_version",
                "ordering": ["-version", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "latency_ms",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="intelligence.promptversion",
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_prompt_usage",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="promptversion",
            index=models.Index(
                fields=["name", "is_active"], name="intelligenc_name_c01cdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptversion",
            index=models.Index(
                fields=["feature", "is_active"], name="intelligenc_feature_d1ceed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promptversion",
            unique_together={("name", "version")},
        ),
        migrations.AddIndex(
            model_name="promptusage",
            index=models.Index(
                fields=["prompt_version", "-created_at"],
                name="intelligenc_prompt__c0454b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptusage",
            index=models.Index(
                fields=["-created_at"], name="intelligenc_created_6497e3_idx"
            ),
        ),
    ]
