# Generated by Django 4.2.16 on 2026-08-01 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('user', 'User Action'), ('job', 'Job Action'), ('search', 'Search Action'), ('ai', 'AI Action'), ('employer', 'Employer Action'), ('system', 'System Event')], db_index=True, max_length=20)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='events_log_event_t_983958_idx'), models.Index(fields=['user', 'event_type', 'created_at'], name='events_log_user_id_bfcefa_idx'), models.Index(fields=['target_type', 'target_id'], name='events_log_target__6b43bc_idx'), models.Index(fields=['category', 'created_at'], name='events_log_categor_492c14_idx')],
            },
        ),
    ]
