# Generated by Django 4.2.16 on 2026-08-07 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('role', 'Role Goal'), ('skill', 'Skill Goal'), ('salary', 'Salary Goal'), ('company', 'Company Goal'), ('learning', 'Learning Goal'), ('certification', 'Certification Goal')], db_index=True, default='role', max_length=20)),
                ('target_role', models.CharField(blank=True, max_length=200)),
                ('target_skill', models.CharField(blank=True, max_length=200)),
                ('target_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_company', models.CharField(blank=True, max_length=200)),
                ('target_certification', models.CharField(blank=True, max_length=200)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('milestones', models.JSONField(default=list, help_text='[{title, due_date, completed}]')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Goal',
                'verbose_name_plural': 'Career Goals',
                'db_table': 'career_goal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_interview_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CareerGoalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='e.g., learning, networking, application', max_length=50)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='career.careergoal')),
            ],
            options={
                'verbose_name': 'Goal Action',
                'verbose_name_plural': 'Goal Actions',
                'db_table': 'career_goal_action',
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
