# Generated by Django 4.2.16 on 2026-08-01 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerBrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('identity', models.JSONField(default=dict, help_text='Career identity, self-perception, professional brand')),
                ('skills', models.JSONField(default=dict, help_text='Skills with proficiency levels: {skill_name: {level, verified, years}}')),
                ('goals', models.JSONField(default=list, help_text='[{goal, priority, timeline, status, milestones}]')),
                ('preferences', models.JSONField(default=dict, help_text='Work style, environment, compensation preferences')),
                ('learning', models.JSONField(default=dict, help_text='Recent learning activity and interests')),
                ('history_summary', models.TextField(blank=True, help_text='AI-generated career history summary')),
                ('ai_observations', models.JSONField(default=dict, help_text='AI-generated insights about the user')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence in the career context (0-1)')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_brain', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Brain',
                'verbose_name_plural': 'Career Brains',
                'db_table': 'career_brain',
            },
        ),
    ]
