# Generated by Django 6.0.6 on 2026-08-28 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0004_migrate_userprofile_data"),
        ("jobs", "0003_remove_job_remote_type_job_work_arrangement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "steps_completed",
                    models.JSONField(
                        default=list,
                        help_text="List of completed step IDs: ['role', 'basic_info', 'career_stage', 'cv_upload', 'preferences', 'goals']",
                    ),
                ),
                (
                    "career_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("student", "Student"),
                            ("junior", "Junior (0-2 years)"),
                            ("mid", "Mid-level (3-5 years)"),
                            ("senior", "Senior (6-10 years)"),
                            ("exec", "Executive (10+ years)"),
                            ("career_change", "Career Change"),
                        ],
                        help_text="Career stage selected during onboarding",
                        max_length=50,
                    ),
                ),
                (
                    "primary_interest",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("find_job", "Find a Job"),
                            ("explore", "Explore Opportunities"),
                            ("improve_skills", "Improve Skills"),
                            ("prepare_interviews", "Prepare for Interviews"),
                        ],
                        help_text="Primary reason for using the platform",
                        max_length=50,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user completed full onboarding",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Progress",
                "verbose_name_plural": "Onboarding Progress",
                "db_table": "career_onboarding_progress",
            },
        ),
        migrations.CreateModel(
            name="CoverLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("content", models.TextField(help_text="Cover letter text")),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version number if user regenerates"
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("enthusiastic", "Enthusiastic"),
                            ("formal", "Formal"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="AI confidence score (0-1)"
                    ),
                ),
                ("word_count", models.IntegerField(default=0)),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="User manually edited this version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_letters",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cover Letter",
                "verbose_name_plural": "Cover Letters",
                "db_table": "career_cover_letter",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "job"], name="career_cove_user_id_526934_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="career_cove_created_e2a517_idx"
                    ),
                ],
            },
        ),
    ]
