# Generated by Django 6.0.6 on 2026-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0005_onboardingprogress_coverletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerprofile",
            name="is_discoverable",
            field=models.BooleanField(
                default=False,
                help_text="If True, employers can find and add this user to talent pools",
            ),
        ),
    ]
