# Generated by Django 6.0.6 on 2026-08-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0007_migrate_min_match_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("url", models.URLField(max_length=500)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("coursera", "Coursera"),
                            ("udemy", "Udemy"),
                            ("edx", "edX"),
                            ("youtube", "YouTube"),
                            ("linkedin_learning", "LinkedIn Learning"),
                            ("pluralsight", "Pluralsight"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "skill_tags",
                    models.JSONField(
                        default=list, help_text="List of skill name strings"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=15,
                    ),
                ),
                ("duration_hours", models.FloatField(blank=True, null=True)),
                ("is_free", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Learning Resource",
                "verbose_name_plural": "Learning Resources",
                "db_table": "career_learning_resource",
                "ordering": ["-rating", "title"],
            },
        ),
    ]
