# Generated by Django 4.2.16 on 2026-08-01 00:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_remove_job_remote_type_job_work_arrangement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('trust_score', models.FloatField(db_index=True, default=0.0)),
                ('ats_platform_detected', models.CharField(blank=True, max_length=50)),
                ('ats_confidence', models.FloatField(default=0.0)),
                ('final_url', models.URLField(blank=True, max_length=2000)),
                ('redirect_chain', models.JSONField(default=list)),
                ('redirect_count', models.IntegerField(default=0)),
                ('domain_trust', models.FloatField(default=0.0)),
                ('domain_matches_company', models.BooleanField(default=False)),
                ('ssl_valid', models.BooleanField(default=False)),
                ('legitimacy_score', models.FloatField(default=0.0)),
                ('legitimacy_flags', models.JSONField(default=list)),
                ('url_accessible', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_duration_ms', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='jobs.job')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='jobs.job')),
            ],
            options={
                'db_table': 'verification_result',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'trust_score'], name='verificatio_status_fe9844_idx'), models.Index(fields=['content_hash'], name='verificatio_content_76cd50_idx')],
            },
        ),
    ]
