# Generated by Django 6.0.6 on 2026-08-28 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationresult",
            name="admin_override",
            field=models.BooleanField(
                default=False,
                help_text="Admin manually approved/rejected this verification",
            ),
        ),
        migrations.AddField(
            model_name="verificationresult",
            name="override_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationresult",
            name="override_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verification_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="verificationresult",
            name="override_reason",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ApprovedATS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Approved ATS domain (e.g., greenhouse.io, lever.co)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="ATS platform name (e.g., 'Greenhouse', 'Lever')",
                        max_length=100,
                    ),
                ),
                (
                    "url_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Optional URL pattern regex for matching (e.g., 'boards.greenhouse.io/*')",
                        max_length=500,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False to temporarily disable this approval",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_ats_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Approved ATS",
                "verbose_name_plural": "Approved ATS Platforms",
                "db_table": "verification_approved_ats",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlockedDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Blocked domain (e.g., apply.indeed.com, linkedin.com/jobs/apply)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Why this domain is blocked (e.g., 'Intermediary application platform')"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False to temporarily disable this block",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_domains_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked Domain",
                "verbose_name_plural": "Blocked Domains",
                "db_table": "verification_blocked_domain",
                "ordering": ["domain"],
            },
        ),
    ]
