# Generated by Django 6.0.6 on 2026-08-28 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("jobseeker", "Job Seeker"),
                    ("employer", "Employer"),
                    ("admin", "Admin"),
                    ("user", "User"),
                ],
                db_index=True,
                default="jobseeker",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (30-day grace period)"),
                            ("cancelled", "Cancelled by user"),
                            ("processing", "Processing deletion"),
                            ("completed", "Completed (anonymized)"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason for deletion (for analytics)",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        help_text="Date when deletion will be executed (30 days from request)"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_deletion_request",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DataExportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to generated export file (S3 or local media)",
                        max_length=500,
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        default=0, help_text="Size of export file in bytes"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Export file deleted after 30 days",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of requester (for audit)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_export_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_data_export_request",
                "ordering": ["-requested_at"],
            },
        ),
    ]
