# Generated by Django 6.0.6 on 2026-08-30 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role_accountdeletionrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtensionToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-chosen label, e.g. 'Chrome on laptop'",
                        max_length=100,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        help_text="First 8 chars for identification", max_length=12
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        default=list,
                        help_text="Allowed scopes: profile_read, jobs_read, autofill_log",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_extensiontoken",
                "ordering": ["-created_at"],
            },
        ),
    ]
