# Generated by Django 4.2.16 on 2026-08-06 18:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_remove_job_remote_type_job_work_arrangement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('esco_uri', models.CharField(db_index=True, help_text='ESCO URI (e.g., http://data.europa.eu/esco/occupation/123456)', max_length=255, unique=True)),
                ('onet_soc_code', models.CharField(blank=True, db_index=True, help_text='O*NET SOC code for cross-referencing', max_length=20)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, help_text='Arabic translation of the occupation name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.IntegerField(default=1, help_text='Hierarchy depth (1=broad, 5=specific)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='skills.occupation')),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupations',
                'db_table': 'skills_occupation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('esco_uri', models.CharField(db_index=True, help_text='ESCO URI (e.g., http://data.europa.eu/esco/skill/123456)', max_length=255, unique=True)),
                ('onet_element_id', models.CharField(blank=True, db_index=True, help_text='O*NET element ID for cross-referencing', max_length=100)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, help_text='Arabic translation of the skill name', max_length=255)),
                ('type', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skill'), ('language', 'Language'), ('tool', 'Tool'), ('framework', 'Framework'), ('methodology', 'Methodology')], db_index=True, default='technical', max_length=20)),
                ('category', models.CharField(choices=[('main_group', 'Main Group'), ('sub_group', 'Sub Group'), ('unit_group', 'Unit Group'), ('skill', 'Skill'), ('detailed_skill', 'Detailed Skill')], db_index=True, default='skill', max_length=20)),
                ('level', models.IntegerField(default=1, help_text='Hierarchy depth (1=broad, 5=specific)')),
                ('description', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for semantic similarity (stored as JSON array)', null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'skills_skill',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('relationship_type', models.CharField(choices=[('related_to', 'Related To'), ('prerequisite_for', 'Prerequisite For'), ('broader_than', 'Broader Than'), ('complementary', 'Complementary'), ('alternative', 'Alternative')], db_index=True, max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='Strength of relationship (0-1)')),
                ('source', models.CharField(choices=[('esco', 'ESCO'), ('onet', 'O*NET'), ('computed', 'Computed'), ('manual', 'Manual')], db_index=True, default='esco', max_length=20)),
                ('from_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='skills.skill')),
                ('to_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Skill Relationship',
                'verbose_name_plural': 'Skill Relationships',
                'db_table': 'skills_relationship',
                'unique_together': {('from_skill', 'to_skill', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='OccupationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('importance', models.FloatField(default=3.0, help_text='Importance rating from O*NET (1-5)')),
                ('level', models.FloatField(default=3.0, help_text='Level rating from O*NET (1-7)')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.occupation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Occupation Skill',
                'verbose_name_plural': 'Occupation Skills',
                'db_table': 'skills_occupation_skill',
                'unique_together': {('occupation', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('importance', models.FloatField(default=3.0, help_text='Importance rating (1-5)')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], db_index=True, default='intermediate', max_length=20)),
                ('source', models.CharField(choices=[('ai', 'AI Extraction'), ('manual', 'Manual'), ('import', 'Import')], db_index=True, default='ai', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Job Skill',
                'verbose_name_plural': 'Job Skills',
                'db_table': 'jobs_job_skill',
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('typical_years', models.FloatField(blank=True, help_text='Typical number of years for this transition', null=True)),
                ('probability', models.FloatField(blank=True, help_text='Probability of this transition occurring (0-1)', null=True)),
                ('required_skills_delta', models.JSONField(blank=True, help_text='Skills needed for transition (stored as JSON)', null=True)),
                ('from_occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths_from', to='skills.occupation')),
                ('to_occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths_to', to='skills.occupation')),
            ],
            options={
                'verbose_name': 'Career Path',
                'verbose_name_plural': 'Career Paths',
                'db_table': 'skills_career_path',
                'unique_together': {('from_occupation', 'to_occupation')},
            },
        ),
    ]
