# Generated by Django 6.0.6 on 2026-06-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="careers_page_url",
            field=models.URLField(
                blank=True, help_text="Company's official careers page"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="domain",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Company website domain (e.g., google.com)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="headquarters",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Admin-verified company"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="company",
            name="size",
            field=models.CharField(
                blank=True, help_text="1-10, 11-50, 51-200, etc.", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="apply_url_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="apply_url_status_code",
            field=models.IntegerField(
                blank=True, help_text="Last HTTP status code from URL check", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="apply_url_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="ats_job_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ATS's own internal job ID",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="ats_platform",
            field=models.CharField(
                blank=True,
                help_text="greenhouse, lever, ashby, workday, etc.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="direct_apply_url",
            field=models.URLField(
                blank=True,
                db_index=True,
                help_text="Direct link to company's application page (no aggregators)",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("freelance", "Freelance"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="is_expired",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="legitimacy_flags",
            field=models.JSONField(
                default=list, help_text="List of flags raised by legitimacy checker"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="legitimacy_score",
            field=models.FloatField(
                blank=True,
                help_text="Score from 0.0 to 1.0, higher is more legitimate",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="raw_data",
            field=models.JSONField(
                blank=True,
                help_text="Original scraped payload for debugging",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="remote_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("onsite", "On-site"),
                ],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_currency_new",
            field=models.CharField(blank=True, default="EGP", max_length=3),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_max_new",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_min_new",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="scraped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="source_raw_url",
            field=models.URLField(
                blank=True,
                help_text="Original aggregator URL (not shown to users)",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("scraped", "Scraped from ATS"),
                    ("employer_posted", "Employer Posted"),
                ],
                db_index=True,
                default="scraped",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="ats_platform",
            field=models.CharField(
                blank=True, help_text="greenhouse, lever, ashby, etc.", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="error_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="jobs_added_last_run",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="jobs_found_last_run",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="source",
            name="last_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="last_run_status",
            field=models.CharField(
                choices=[
                    ("never", "Never Run"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="never",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="requires_playwright",
            field=models.BooleanField(
                default=False, help_text="Whether this source needs headless browser"
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="schedule_cron",
            field=models.CharField(
                default="0 */6 * * *",
                help_text="Cron expression for scraping schedule",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="scraper_class",
            field=models.CharField(
                blank=True,
                help_text="Python class name for this scraper",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="about",
            field=models.TextField(blank=True, help_text="Full company description"),
        ),
        migrations.AlterField(
            model_name="company",
            name="snippet",
            field=models.CharField(
                blank=True, help_text="Short company description", max_length=300
            ),
        ),
    ]
