# Generated by Django 4.2.16 on 2026-08-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_company_careers_page_url_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='remote_type',
        ),
        migrations.AddField(
            model_name='job',
            name='work_arrangement',
            field=models.CharField(blank=True, choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], db_index=True, max_length=10, null=True),
        ),
    ]
