# Generated by Django 4.2.16 on 2026-08-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_company_careers_page_url_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='remote_type',
        ),
        migrations.AddField(
            model_name='job',
            name='work_arrangement',
            field=models.CharField(blank=True, choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status'], name='jobs_job_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source', 'status'], name='jobs_job_source_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['ats_platform', 'ats_job_id'], name='jobs_job_ats_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['legitimacy_score'], name='jobs_job_legitimacy_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['expires_at', 'is_expired'], name='jobs_job_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['scraped_at'], name='jobs_job_scraped_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['direct_apply_url'], name='jobs_job_direct_apply_idx'),
        ),
    ]
