# Generated by Django 6.0.6 on 2026-08-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_remove_job_remote_type_job_work_arrangement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="expired_reason",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="job",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="quality_state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("probably_active", "Probably Active"),
                    ("needs_verification", "Needs Verification"),
                    ("expired", "Expired"),
                    ("archived", "Archived"),
                    ("broken", "Broken"),
                    ("duplicate", "Duplicate"),
                    ("rejected", "Rejected"),
                    ("direct_verified", "Direct-source Verified"),
                ],
                db_index=True,
                default="needs_verification",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending Review"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["quality_state"], name="jobs_job_quality_state_idx"
            ),
        ),
    ]
