# Generated by Django 6.0.6 on 2026-08-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_populate_quality_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="github_org",
            field=models.CharField(
                blank=True,
                help_text="GitHub organization handle (e.g., 'google' for github.com/google)",
                max_length=100,
            ),
        ),
    ]
