# Generated by Django 6.0.6 on 2026-08-30 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_add_github_org_to_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="salary_currency_new",
        ),
        migrations.RemoveField(
            model_name="job",
            name="salary_max_new",
        ),
        migrations.RemoveField(
            model_name="job",
            name="salary_min_new",
        ),
    ]
