# Generated by Django 6.0.6 on 2026-09-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_remove_stale_salary_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="field_provenance",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-field lineage for extracted data. Maps a field name to {value, source, method, confidence}. Additive; the raw source payload is preserved separately in raw_data.",
            ),
        ),
    ]
