# Generated by Django 6.0.6 on 2026-10-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_source_lifecycle_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("government", "Government"),
                    ("university", "University"),
                    ("ngo", "NGO / Non-profit"),
                ],
                db_index=True,
                default="business",
                help_text="Organization kind — reuses the same hiring/team/billing stack for all audiences",
                max_length=20,
            ),
        ),
    ]
