# Generated by Django 6.0.6 on 2026-10-02 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_company_org_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyResolutionIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        db_index=True,
                        help_text="ATS platform this tenant was observed on (greenhouse, lever, ashby, ...)",
                        max_length=30,
                    ),
                ),
                (
                    "tenant_slug",
                    models.CharField(
                        db_index=True,
                        help_text="The company's slug/tenant id on that ATS platform",
                        max_length=150,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Company domain observed at the time this identity was resolved, if any",
                        max_length=255,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="How confident this (platform, tenant_slug) -> Company mapping is",
                    ),
                ),
                (
                    "matched_by",
                    models.CharField(
                        blank=True,
                        help_text="How this identity's Company was determined: domain | slug | created",
                        max_length=20,
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Supporting evidence for this resolution (auditability)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution_identities",
                        to="jobs.company",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        help_text="The scraper Source this identity was first resolved from, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_company_identities",
                        to="jobs.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Resolution Identity",
                "verbose_name_plural": "Company Resolution Identities",
                "db_table": "jobs_company_resolution_identity",
                "indexes": [
                    models.Index(fields=["company"], name="jobs_cri_company_idx")
                ],
                "unique_together": {("platform", "tenant_slug")},
            },
        ),
    ]
