# Generated by Django 6.0.6 on 2026-10-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_companyresolutionidentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="adaptive_allowed",
            field=models.BooleanField(
                default=True,
                help_text="If False, this source's Tier-3 adaptive (Scrapling) fallback is disabled even if its platform is unstructured - an admin kill-switch for a specific flaky/legal-sensitive source without having to disable adaptive extraction platform-wide. Read by apps.scraper.tasks._adaptive_fallback_runner.",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="country",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Primary country this source's postings target (admin/matrix metadata)",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="historical_average_jobs",
            field=models.FloatField(
                default=0.0,
                help_text="Exponential moving average of jobs_found_last_run across runs, updated each run. Consumed by anomaly detection to flag 'historical average 700, current run 0' style regressions instead of comparing against a hardcoded threshold.",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="industry",
            field=models.CharField(
                blank=True,
                help_text="Industry focus if this source is industry-specific (free text, admin metadata)",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="last_failure_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="last_nonzero_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last run where jobs_found_last_run > 0 - lets anomaly detection measure exactly how long a source has been silently zero, not just whether its LAST run was zero.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="last_success_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last run that completed without a fetch/dispatch exception (distinct from last_run_at, which also records failed runs)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="legal_review_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not Required"),
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="not_required",
                help_text="Legal review status (e.g. required before enabling an aggregator-adjacent or outreach-adjacent source)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="max_jobs_per_run",
            field=models.IntegerField(
                blank=True,
                help_text="Hard cap on jobs persisted from a single run of this source (bounded-ingestion control for scale testing / a newly-added source). Null = no cap.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Free-text admin notes about this source"
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="rate_limit_override",
            field=models.IntegerField(
                blank=True,
                help_text="Requests/minute override for this source, replacing the platform-wide default in ScraperOrchestrator.RATE_LIMITS. Null = use the platform default.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Region/market grouping (e.g. MENA, EU, NA) - admin/matrix metadata",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="terms_review_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not Required"),
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="not_required",
                help_text="ToS/robots.txt compliance review status for this source",
                max_length=20,
            ),
        ),
    ]
