# Generated by Django 6.0.6 on 2026-10-06 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_source_adaptive_allowed_source_country_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verification_required", "Verification Required"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=25,
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("corporate_email", "Corporate Email Domain Match"),
                            ("dns_txt", "DNS TXT Record Challenge"),
                            ("document", "Uploaded Document (Manual Review)"),
                            ("admin_manual", "Admin Manual Verification"),
                        ],
                        db_index=True,
                        help_text="How the claimant is proving ownership",
                        max_length=20,
                    ),
                ),
                (
                    "claimant_email_domain",
                    models.CharField(
                        blank=True,
                        help_text="Domain portion of claimant's account email at claim time (for corporate_email evidence)",
                        max_length=255,
                    ),
                ),
                (
                    "is_free_mail_domain",
                    models.BooleanField(
                        default=False,
                        help_text="True if claimant_email_domain is a known free/consumer mail provider (gmail.com, etc) - such a match is NEVER sufficient evidence on its own",
                    ),
                ),
                (
                    "dns_challenge_token",
                    models.CharField(
                        blank=True,
                        help_text="Random token the claimant must publish as a TXT record (dns_txt evidence only)",
                        max_length=64,
                    ),
                ),
                ("dns_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Automated confidence this claim's evidence proves real ownership (0.0-1.0); NEVER auto-approves above a conservative threshold - admin review is always the final gate for anything but an exact dns_txt or corporate_email match on a non-free domain",
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Supporting evidence detail (domain comparison, DNS lookup result, document reference, admin note)",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded proof document for 'document' evidence type",
                        null=True,
                        upload_to="company_claim_documents/",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "claimant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="jobs.company",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_claims_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Claim",
                "verbose_name_plural": "Company Claims",
                "db_table": "jobs_company_claim",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="jobs_claim_company_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["pending", "verification_required", "under_review"],
                            )
                        ),
                        fields=("company", "claimant"),
                        name="uniq_active_claim_per_company_claimant",
                    )
                ],
            },
        ),
    ]
