# Generated by Django 6.0.6 on 2026-10-06 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_companyclaim"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyEnrichment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("domain", "Domain"),
                            ("careers_page_url", "Careers Page URL"),
                            ("industry", "Industry"),
                            ("headquarters", "Headquarters"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "method",
                    models.CharField(
                        help_text="How this value was derived: resolution_identity_domain | ats_board_url_pattern | source_industry_backfill | job_location_majority. Every method reuses evidence this platform already ingested — none of them scrape or fabricate new external data.",
                        max_length=40,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "applied",
                    models.BooleanField(
                        default=False,
                        help_text="True if this value was actually written to the Company field (only ever happens when that field was blank)",
                    ),
                ),
                (
                    "conflict",
                    models.BooleanField(
                        default=False,
                        help_text="True if this evidence disagrees with an existing non-blank Company field value (flagged for admin review, never auto-overwritten)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichments",
                        to="jobs.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Enrichment",
                "verbose_name_plural": "Company Enrichments",
                "db_table": "jobs_company_enrichment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "field_name"],
                        name="jobs_enrich_company_field_idx",
                    )
                ],
            },
        ),
    ]
