# Generated by Django 6.0.6 on 2026-10-06 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_companyenrichment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "role_prefix",
                    models.CharField(
                        help_text="The generic role this address represents (careers, jobs, hr, talent, recruiting, hiring, people, info, contact)",
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "domain_pattern_guess",
                                "Domain Pattern Guess (unverified)",
                            ),
                            ("admin_manual", "Admin Manual Entry"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="0.3 for an unverified pattern guess; set higher only by explicit admin confirmation",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="True only if a human has confirmed this address is real and current",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_do_not_contact",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Suppression flag - Outreach must never address a message to this contact when True",
                    ),
                ),
                ("do_not_contact_reason", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_contacts",
                        to="jobs.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Contact",
                "verbose_name_plural": "Business Contacts",
                "db_table": "jobs_business_contact",
                "ordering": ["company__name", "role_prefix"],
                "indexes": [
                    models.Index(
                        fields=["company", "is_do_not_contact"],
                        name="jobs_contact_company_dnc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "email"),
                        name="uniq_business_contact_per_company_email",
                    )
                ],
            },
        ),
    ]
