# Generated by Django 4.2.16 on 2026-08-07 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='My Resume', max_length=200)),
                ('personal_info', models.JSONField(default=dict, help_text='Personal information (name, email, phone, etc.)')),
                ('summary', models.TextField(blank=True, help_text='Professional summary')),
                ('experience', models.JSONField(default=list, help_text='Work experience list')),
                ('education', models.JSONField(default=list, help_text='Education list')),
                ('skills', models.JSONField(default=list, help_text='Skills list')),
                ('projects', models.JSONField(default=list, help_text='Projects list')),
                ('certifications', models.JSONField(default=list, help_text='Certifications list')),
                ('languages', models.JSONField(default=list, help_text='Languages list')),
                ('interests', models.JSONField(default=list, help_text='Interests list')),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('privacy_settings', models.JSONField(default=dict, help_text='Privacy settings for resume sections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('modern', 'Modern'), ('professional', 'Professional'), ('creative', 'Creative'), ('academic', 'Academic'), ('minimalist', 'Minimalist'), ('technical', 'Technical')], db_index=True, max_length=20)),
                ('preview_image', models.URLField(blank=True, help_text='URL to template preview image')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('used_count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume Template',
                'verbose_name_plural': 'Resume Templates',
                'db_table': 'resume_template',
            },
        ),
        migrations.CreateModel(
            name='ResumeExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('html', 'HTML'), ('json', 'JSON')], db_index=True, max_length=10)),
                ('file_url', models.URLField(blank=True, help_text='URL to exported file')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if export failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='resume.resume')),
            ],
            options={
                'verbose_name': 'Resume Export',
                'verbose_name_plural': 'Resume Exports',
                'db_table': 'resume_export',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='resume.resumetemplate'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('section_type', models.CharField(choices=[('summary', 'Summary'), ('experience', 'Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects'), ('certifications', 'Certifications'), ('languages', 'Languages'), ('interests', 'Interests')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.JSONField(default=dict, help_text='Section content')),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Section',
                'verbose_name_plural': 'Profile Sections',
                'db_table': 'profile_section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_category', models.CharField(blank=True, max_length=50)),
                ('verification_method', models.CharField(choices=[('assessment', 'Assessment passed'), ('github', 'GitHub analysis'), ('project', 'Project evidence'), ('endorsement', 'Endorsement'), ('certification', 'Certification'), ('cv', 'CV extraction')], db_index=True, max_length=20)),
                ('evidence_url', models.URLField(blank=True, help_text='URL to evidence (GitHub, portfolio, etc.)')),
                ('evidence_text', models.TextField(blank=True, help_text='Evidence text (for CV extraction)')),
                ('score', models.IntegerField(blank=True, help_text='Skill score (0-100)', null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], db_index=True, default='intermediate', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Verification expiration date', null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_verifications', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Verification',
                'verbose_name_plural': 'Skill Verifications',
                'db_table': 'skill_verification',
                'unique_together': {('user', 'skill_name')},
            },
        ),
    ]
