# Generated by Django 4.2.16 on 2026-08-06 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_remove_job_remote_type_job_work_arrangement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('insight_type', models.CharField(choices=[('user_underpaid', 'User is underpaid'), ('user_above_market', 'User is above market'), ('user_negotiation', 'User should negotiate'), ('employer_low_range', 'Employer salary range is too low'), ('employer_high_range', 'Employer salary range is competitive')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_points', models.JSONField(default=dict, help_text='Data points supporting the insight')),
                ('is_actionable', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.CharField(default='haiku', help_text='AI model used to generate insight', max_length=50)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_insights', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Insight',
                'verbose_name_plural': 'Salary Insights',
                'db_table': 'salary_insight',
            },
        ),
        migrations.CreateModel(
            name='SalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary (annualized)', max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary (annualized)', max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', help_text='ISO 4217 currency code (e.g., USD, EUR, EGP)', max_length=3)),
                ('frequency', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('hourly', 'Hourly')], db_index=True, default='yearly', max_length=20)),
                ('source', models.CharField(blank=True, help_text="'job_posting', 'user_reported', 'employer_input'", max_length=50)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this salary has been verified')),
                ('annualized_salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Annualized minimum salary', max_digits=12, null=True)),
                ('annualized_salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Annualized maximum salary', max_digits=12, null=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_data', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Salary Data',
                'verbose_name_plural': 'Salary Data',
                'db_table': 'salary_data',
            },
        ),
        migrations.CreateModel(
            name='SalaryBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=20)),
                ('user_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('market_median', models.DecimalField(decimal_places=2, help_text='Market median salary', max_digits=12)),
                ('market_25th', models.DecimalField(decimal_places=2, help_text='Market 25th percentile', max_digits=12)),
                ('market_75th', models.DecimalField(decimal_places=2, help_text='Market 75th percentile', max_digits=12)),
                ('below_market_by', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage below market median', max_digits=5, null=True)),
                ('percentile_rank', models.IntegerField(blank=True, help_text="User's percentile rank in market", null=True)),
                ('is_underpaid', models.CharField(choices=[('yes', 'Yes - Significantly underpaid'), ('maybe', 'Maybe - Slightly underpaid'), ('fair', 'Fair - Around market rate'), ('above', 'Above - Above market rate')], default='fair', max_length=10)),
                ('negotiation_tips', models.JSONField(default=list, help_text='AI-generated negotiation tips')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_benchmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Benchmark',
                'verbose_name_plural': 'Salary Benchmarks',
                'db_table': 'salary_benchmark',
            },
        ),
        migrations.CreateModel(
            name='SalaryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('alert_type', models.CharField(choices=[('market_increase', 'Market rate increased'), ('user_below_new_market', 'User salary now below new market'), ('new_high_paying_job', 'New high-paying job match')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('significant', 'Significant')], default='moderate', max_length=20)),
                ('action_url', models.URLField(blank=True, help_text='URL to take action')),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Alert',
                'verbose_name_plural': 'Salary Alerts',
                'db_table': 'salary_alert',
            },
        ),
        migrations.CreateModel(
            name='MarketRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(db_index=True, help_text="Job title (e.g., 'Senior Backend Engineer')", max_length=100)),
                ('location', models.CharField(db_index=True, help_text="Location (e.g., 'Dubai, UAE')", max_length=100)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry (0-2 years)'), ('junior', 'Junior (2-5 years)'), ('mid', 'Mid (5-8 years)'), ('senior', 'Senior (8-12 years)'), ('lead', 'Lead (12+ years)')], db_index=True, max_length=20)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3)),
                ('percentile_25', models.DecimalField(decimal_places=2, help_text='25th percentile salary', max_digits=12)),
                ('percentile_50', models.DecimalField(decimal_places=2, help_text='50th percentile (median) salary', max_digits=12)),
                ('percentile_75', models.DecimalField(decimal_places=2, help_text='75th percentile salary', max_digits=12)),
                ('percentile_90', models.DecimalField(decimal_places=2, help_text='90th percentile salary', max_digits=12)),
                ('sample_size', models.IntegerField(default=1, help_text='Number of job postings used for calculation')),
                ('data_last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Rate',
                'verbose_name_plural': 'Market Rates',
                'db_table': 'market_rate',
                'unique_together': {('role', 'location', 'experience_level')},
            },
        ),
    ]
