# Generated by Django 6.0.6 on 2026-09-24 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_add_subscription_plan_and_company_subscription"),
        ("jobs", "0007_remove_stale_salary_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed amount")],
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.BigIntegerField(
                        help_text="Percent (0-100) or fixed minor units"
                    ),
                ),
                (
                    "max_redemptions",
                    models.IntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("times_redeemed", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "payments_coupon",
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=160, unique=True)),
                (
                    "scope",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. 'payment.create', 'webhook.process'",
                        max_length=60,
                    ),
                ),
                (
                    "result_ref",
                    models.CharField(
                        blank=True,
                        help_text="Reference of the object produced",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payments_idempotency_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("total", models.BigIntegerField(default=0)),
                (
                    "currency",
                    models.CharField(
                        choices=[("EGP", "Egyptian Pound"), ("USD", "US Dollar")],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payments_invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "platform_code",
                    models.CharField(
                        choices=[
                            ("C", "Career"),
                            ("E", "Education"),
                            ("F", "Freelancing"),
                            ("K", "Kids"),
                        ],
                        db_index=True,
                        default="C",
                        max_length=1,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "payments_ledger_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("entity_type", models.CharField(blank=True, max_length=60)),
                (
                    "entity_ref",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("correlation_id", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_financial_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                ("unit_amount", models.BigIntegerField(default=0)),
                ("amount", models.BigIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "payments_invoice_item",
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Stable machine code, e.g. 'revenue:career'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("revenue", "Revenue"),
                            ("refund", "Refund"),
                            ("fees", "Fees"),
                            ("escrow", "Escrow"),
                        ],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_ledger_account",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "platform_code",
                    models.CharField(
                        choices=[
                            ("C", "Career"),
                            ("E", "Education"),
                            ("F", "Freelancing"),
                            ("K", "Kids"),
                        ],
                        db_index=True,
                        default="C",
                        max_length=1,
                    ),
                ),
                ("subtotal", models.BigIntegerField(default=0)),
                ("discount", models.BigIntegerField(default=0)),
                ("total", models.BigIntegerField(default=0)),
                (
                    "currency",
                    models.CharField(
                        choices=[("EGP", "Egyptian Pound"), ("USD", "US Dollar")],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending payment"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="jobs.company",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="payments.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="payments.order",
            ),
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("employer", "Employer"),
                        ],
                        db_index=True,
                        default="employer",
                        max_length=20,
                    ),
                ),
                (
                    "platform_code",
                    models.CharField(
                        choices=[
                            ("C", "Career"),
                            ("E", "Education"),
                            ("F", "Freelancing"),
                            ("K", "Kids"),
                        ],
                        db_index=True,
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "price_amount",
                    models.BigIntegerField(default=0, help_text="Minor units"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("EGP", "Egyptian Pound"), ("USD", "US Dollar")],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("one_time", "One-time"),
                            ("month", "Monthly"),
                            ("year", "Yearly"),
                        ],
                        default="one_time",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "entitlement_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Entitlement granted when this package is purchased",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="core.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "payments_package",
                "ordering": ["audience", "price_amount"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="payments.package",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "platform_code",
                    models.CharField(
                        choices=[
                            ("C", "Career"),
                            ("E", "Education"),
                            ("F", "Freelancing"),
                            ("K", "Kids"),
                        ],
                        db_index=True,
                        default="C",
                        max_length=1,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                (
                    "currency",
                    models.CharField(
                        choices=[("EGP", "Egyptian Pound"), ("USD", "US Dollar")],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=12,
                    ),
                ),
                (
                    "provider",
                    models.CharField(db_index=True, default="", max_length=40),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ledger_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="payments.ledgertransaction",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.order",
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("http_status", models.IntegerField(blank=True, null=True)),
                ("succeeded", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment_attempt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("amount", models.BigIntegerField()),
                (
                    "currency",
                    models.CharField(
                        choices=[("EGP", "Egyptian Pound"), ("USD", "US Dollar")],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=12,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "ledger_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="payments.ledgertransaction",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payments_refund",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=40)),
                ("provider_event_id", models.CharField(db_index=True, max_length=200)),
                ("event_type", models.CharField(blank=True, max_length=100)),
                ("signature_valid", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("verified", "Verified"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=12,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.CharField(blank=True, max_length=120)),
                ("error", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "payments_webhook_event",
                "ordering": ["-received_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_event_id"),
                        name="uniq_provider_event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "amount",
                    models.BigIntegerField(
                        help_text="Signed minor units; + credit, - debit"
                    ),
                ),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="payments.ledgeraccount",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="payments.ledgertransaction",
                    ),
                ),
            ],
            options={
                "db_table": "payments_ledger_entry",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "created_at"], name="ledger_entry_acct_idx"
                    )
                ],
            },
        ),
    ]
