# Generated by Django 6.0.6 on 2026-09-26 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdjustmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "platform_code",
                    models.CharField(
                        choices=[
                            ("C", "Career"),
                            ("E", "Education"),
                            ("F", "Freelancing"),
                            ("K", "Kids"),
                        ],
                        db_index=True,
                        default="C",
                        max_length=1,
                    ),
                ),
                ("account_code", models.CharField(max_length=100)),
                ("counter_account_code", models.CharField(max_length=100)),
                (
                    "amount",
                    models.BigIntegerField(
                        help_text="Signed minor units applied to account_code"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("EGP", "Egyptian Pound"), ("USD", "US Dollar")],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("approved", "Approved (posted)"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustment_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="payments.ledgertransaction",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_adjustment_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
