# Generated by Django 4.2.16 on 2026-08-06 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('assessment_type', models.CharField(choices=[('coding', 'Coding Challenge'), ('multiple_choice', 'Multiple Choice Quiz'), ('essay', 'Essay/Text Response'), ('practical', 'Practical Task')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], db_index=True, default='intermediate', max_length=20)),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Time limit in minutes (null = no limit)', null=True)),
                ('max_attempts', models.IntegerField(default=3, help_text='Maximum number of attempts allowed')),
                ('passing_score', models.IntegerField(default=70, help_text='Minimum score to pass (0-100)')),
                ('total_points', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_created', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='assessments', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'assessment',
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('attempt_number', models.IntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('expired', 'Expired')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, help_text='Score (0-100)', null=True)),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(default=dict, help_text="User's answers")),
                ('feedback', models.JSONField(default=dict, help_text='AI-generated feedback')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Attempt',
                'verbose_name_plural': 'Assessment Attempts',
                'db_table': 'assessment_attempt',
                'unique_together': {('user', 'assessment', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_role', models.CharField(max_length=100)),
                ('time_limit_minutes', models.IntegerField(default=30)),
                ('max_attempts', models.IntegerField(default=3)),
                ('passing_score', models.IntegerField(default=70)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('assessment_type', models.CharField(choices=[('coding', 'Coding Challenge'), ('multiple_choice', 'Multiple Choice Quiz'), ('essay', 'Essay/Text Response'), ('practical', 'Practical Task')], default='coding', max_length=20)),
                ('status', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('featured', 'Featured')], db_index=True, default='public', max_length=20)),
                ('used_count', models.IntegerField(default=0)),
                ('skills', models.ManyToManyField(blank=True, related_name='assessment_templates', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Assessment Template',
                'verbose_name_plural': 'Assessment Templates',
                'db_table': 'assessment_template',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('total_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('question_scores', models.JSONField(default=dict, help_text='Scores per question')),
                ('time_per_question', models.JSONField(default=dict, help_text='Time spent per question')),
                ('ai_analysis', models.JSONField(default=dict, help_text='AI-generated analysis')),
                ('strengths', models.JSONField(default=list, help_text='Identified strengths')),
                ('weaknesses', models.JSONField(default=list, help_text='Identified weaknesses')),
                ('recommendations', models.JSONField(default=list, help_text='Improvement recommendations')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessment.assessmentattempt')),
            ],
            options={
                'verbose_name': 'Assessment Result',
                'verbose_name_plural': 'Assessment Results',
                'db_table': 'assessment_result',
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('question_type', models.CharField(choices=[('coding', 'Coding Challenge'), ('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('essay', 'Essay/Text Response')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starter_code', models.TextField(blank=True, help_text='Starter code for coding questions')),
                ('test_cases', models.JSONField(default=list, help_text='Test cases for coding questions')),
                ('options', models.JSONField(default=list, help_text='Answer options for multiple choice')),
                ('correct_answer', models.JSONField(help_text='Correct answer(s)')),
                ('points', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.assessment')),
            ],
            options={
                'verbose_name': 'Assessment Question',
                'verbose_name_plural': 'Assessment Questions',
                'db_table': 'assessment_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.CharField(choices=[('verified', 'Verified'), ('proficient', 'Proficient'), ('expert', 'Expert')], db_index=True, default='verified', max_length=20)),
                ('verification_method', models.CharField(choices=[('assessment', 'Assessment passed'), ('github', 'GitHub analysis'), ('endorsement', 'Endorsement'), ('cv', 'CV extraction')], db_index=True, default='assessment', max_length=20)),
                ('score', models.IntegerField(blank=True, help_text='Score from assessment (0-100)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Badge expiration date (null = never expires)', null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Badge',
                'verbose_name_plural': 'Skill Badges',
                'db_table': 'skill_badge',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
